### ISSUE TITLE
项目还在维护吗

### ISSUE THREAD

**Issue by wwhai** [shootingfans/codec_gb26875_3_2011#1]
# 项目还在维护吗

**Comment by jarod2011** [comment]
是的，在维护

**Comment by jarod2011** [comment]
> # 项目还在维护吗

是的，在维护

**Comment by wwhai** [comment]
> > # 项目还在维护吗
> 
> 是的，在维护
多谢.近期学习一下

**Comment by jarod2011** [comment]
> > > # 项目还在维护吗
> > 
> > 
> > 是的，在维护
> > 多谢.近期学习一下

OK，那我关闭issue了？
