### ISSUE TITLE
客户端请求后是否有应答数据

### ISSUE THREAD

**Issue by crazy-cpu** [shootingfans/codec_gb26875_3_2011#2]
按照协议中的规定，信息装置向监控中心发送消息后需要监控中心回复应答数据，反之也一样。我查看了代码，没有找到这部分逻辑。

**Comment by jarod2011** [comment]
The Client(Transmission) send msg to Server, The Action is `constants.SendDataAction`.
When Server receive the msg, reply `constants.AckAction` for success or `constants.RejectAction` for failure.

**Comment by jarod2011** [comment]
This project is only the codec for GBT26875.3-2011.
You can read the <<GBT26875.3-2011>> and use this project to Encode or Decode the schema.

**Comment by crazy-cpu** [comment]
好的，这部分逻辑需要自己实现，这里只是提供了协议的编码和解码。如果我不实现它的话，会不停的触发客户端的重传机制

**Comment by jarod2011** [comment]
> 好的，这部分逻辑需要自己实现，这里只是提供了协议的编码和解码。如果我不实现它的话，会不停的触发客户端的重传机制

Yes, This package is only a codec, Not a server.
You can see example, I add server reply client request to server example and add client read response
